blank_issues_enabled: true
contact_links:
  - name: Ask a question
    url: https://github.com/omar-dulaimi/prisma-valibot-generator/discussions/new
    about: Ask questions and discuss with others
  - name: 💖 Sponsor this project
    url: https://github.com/sponsors/omar-dulaimi
    about: Help keep the project actively maintained and support new features